ALTER TABLE player_stats
    ADD COLUMN career_balls_faced BIGINT DEFAULT 0,
    ADD COLUMN career_innings_batted BIGINT DEFAULT 0,
    ADD COLUMN career_not_outs BIGINT DEFAULT 0,
    ADD COLUMN career_highest_score INTEGER DEFAULT 0,
    ADD COLUMN career_ducks BIGINT DEFAULT 0,
    ADD COLUMN career_golden_ducks BIGINT DEFAULT 0,
    ADD COLUMN career_fifties BIGINT DEFAULT 0,
    ADD COLUMN career_hundreds BIGINT DEFAULT 0,
    ADD COLUMN career_balls_bowled BIGINT DEFAULT 0,
    ADD COLUMN career_runs_conceded BIGINT DEFAULT 0,
    ADD COLUMN career_maiden_overs BIGINT DEFAULT 0,
    ADD COLUMN career_wides BIGINT DEFAULT 0,
    ADD COLUMN career_no_balls BIGINT DEFAULT 0,
    ADD COLUMN career_best_bowling_wickets INTEGER DEFAULT 0,
    ADD COLUMN career_best_bowling_runs INTEGER DEFAULT 0,
    ADD COLUMN career_innings_bowled BIGINT DEFAULT 0,
    ADD COLUMN career_matches_won BIGINT DEFAULT 0,
    ADD COLUMN career_matches_lost BIGINT DEFAULT 0,
    ADD COLUMN career_total_points BIGINT DEFAULT 0,
    ADD COLUMN career_mvps BIGINT DEFAULT 0,
    ADD COLUMN archived_at TIMESTAMP;